/*
 *  Copyright 2008 The Apache Software Foundation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.apache.ibatis.ibator.api;

import java.util.List;
import java.util.Properties;

import org.apache.ibatis.ibator.api.dom.java.Interface;
import org.apache.ibatis.ibator.api.dom.java.Method;
import org.apache.ibatis.ibator.api.dom.java.TopLevelClass;
import org.apache.ibatis.ibator.api.dom.xml.Document;
import org.apache.ibatis.ibator.api.dom.xml.XmlElement;
import org.apache.ibatis.ibator.config.IbatorContext;

/**
 * This interface defines methods that will be called by ibator at different
 * times during the code generation process.  These methods can be used to
 * extend or modify the code generated by ibator.  Clients may implement this
 * interface in its entirety, or extend the IbatorPluginAdapter (highly recomended).
 * <p>
 * Plugins have a lifecycle.  In general, the lifecycle is this:
 * 
 * <ol>
 *   <li>The setXXX methods are called one time</li>
 *   <li>The validate method is called one time</li>
 *   <li>The daoXXX methods are called for each introspected table</li>
 *   <li>The modelXXX methods are called for each introspected table</li>
 *   <li>The sqlMapXXX methods are called for each introspected table</li>
 *   <li>The contextGenerateAdditionalJavaFiles(IntrospectedTable) method is
 *       called for each introspected table</li>
 *   <li>The contextGenerateAdditionalXmlFiles(IntrospectedTable) method is
 *       called for each introspected table</li>
 *   <li>The contextGenerateAdditionalJavaFiles() method is
 *       called one time</li>
 *   <li>The contextGenerateAdditionalXmlFiles() method is
 *       called one time</li>
 * </ol>
 * 
 * Plugins are related to ibator contexts - so each context will have its
 * own set of plugins.  If the same plugin is specified in multple contexts,
 * then each context will hold a unique instance of the plugin.
 * <p>
 * Plugins are called, and initialized, in the same order they are specified
 * in the configuration.
 * <p>The daoXXX, modelXXX, and sqlMapXXX methods are called by the code
 * generators supplied with ibator.  If you replace ibator's default code
 * generators with other implementations, these methods may not be called.
 * 
 * @author Jeff Butler
 * @see IbatorPluginAdapter
 *
 */
public interface IbatorPlugin {
    /**
     * Set the context under which this plugin is running
     * 
     * @param ibatorContext
     */
    void setIbatorContext(IbatorContext ibatorContext);
    
    /**
     * Set properties from the plugin configuration
     * 
     * @param properties
     */
    void setProperties(Properties properties);
    
    /**
     * This method is called after all the setXXX methods are called, but before any
     * other method is called.  This allows the plugin to determine whether
     * it can run or not.  For example, if the plugin requires certain properties
     * to be set, and the properties are not set, then the plugin is invalid
     * and will not run.
     * 
     * @param warnings add strings to this list to specify warnings.  For example,
     *   if the plugin is invalid, you should specify why.  Warnings are reported
     *   to users after the completion of the ibator run.
     * @return true if the plugin is in a valid state.  Invalid plugins will not be
     *   called
     */
    boolean validate(List<String> warnings);
    
    /**
     * This method can be used to generate any additional Java file needed
     * by your implementation.
     * This method is called once, after all other Java files have been 
     * generated.
     * 
     * @return a List of GeneratedJavaFiles - ibator will persist these
     *    files with the other files from this run of ibator.
     */
    List<GeneratedJavaFile> contextGenerateAdditionalJavaFiles();
    
    /**
     * This method can be used to generate additional Java files needed
     * by your implementation that might be related to a specific table.
     * This method is called once for every table in the configuration.
     * 
     * @param introspectedTable ibator's class containing information
     *   about the table as introspected from the database
     * @return a List of GeneratedJavaFiles - ibator will persist these
     *    files with the other files from this run of ibator.
     */
    List<GeneratedJavaFile> contextGenerateAdditionalJavaFiles(IntrospectedTable introspectedTable);

    /**
     * This method can be used to generate any additional XML file needed
     * by your implementation.
     * This method is called once, after all other XML files have been 
     * generated.
     * 
     * @return a List of GeneratedXmlFiles - ibator will persist these
     *    files with the other files from this run of ibator.
     */
    List<GeneratedXmlFile> contextGenerateAdditionalXmlFiles();
    
    /**
     * This method can be used to generate additional XML files needed
     * by your implementation that might be related to a specific table.
     * This method is called once for every table in the configuration.
     * 
     * @param introspectedTable ibator's class containing information
     *   about the table as introspected from the database
     * @return a List of GeneratedXmlFiles - ibator will persist these
     *    files with the other files from this run of ibator.
     */
    List<GeneratedXmlFile> contextGenerateAdditionalXmlFiles(IntrospectedTable introspectedTable);

    void daoInterfaceGenerated(Interface interfaze, IntrospectedTable introspectedTable);
    void daoImplementationGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoCountByExampleMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoCountByExampleMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoDeleteByExampleMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoDeleteByExampleMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoDeleteByPrimaryKeyMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoDeleteByPrimaryKeyMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoInsertMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoInsertMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoSelectByExampleWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoSelectByExampleWithBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoSelectByExampleWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoSelectByExampleWithoutBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoSelectByPrimaryKeyMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoSelectByPrimaryKeyMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoUpdateByExampleSelectiveMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoUpdateByExampleSelectiveMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoUpdateByExampleWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoUpdateByExampleWithBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoUpdateByExampleWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoUpdateByExampleWithoutBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoUpdateByPrimaryKeySelectiveMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoUpdateByPrimaryKeySelectiveMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoUpdateByPrimaryKeyWithBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoUpdateByPrimaryKeyWithBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);
    void daoUpdateByPrimaryKeyWithoutBLOBsMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    void daoUpdateByPrimaryKeyWithoutBLOBsMethodGenerated(Method method, Interface interfaze, IntrospectedTable introspectedTable);

    /**
     * This method is called after the primary key class is generated by
     * the ibator supplied JavaModelGenerator.  This method will only be
     * called if the table rules call for generation of a primary key class.
     * <p/>
     * This method is only guaranteed to be called by the ibator
     * supplied Java model generators.  Other user supplied generators
     * may, or may not, call this method.
     * 
     * @param topLevelClass the generated primary key class
     * @param introspectedTable ibator's class containing information
     *   about the table as introspected from the database
     */
    void modelPrimaryKeyClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable);

    /**
     * This method is called after the base record class is generated by
     * the ibator supplied JavaModelGenerator.  This method will only be
     * called if the table rules call for generation of a base record class.
     * <p/>
     * This method is only guaranteed to be called by the ibator
     * supplied Java model generators.  Other user supplied generators
     * may, or may not, call this method.
     * 
     * @param topLevelClass the generated base record class
     * @param introspectedTable ibator's class containing information
     *   about the table as introspected from the database
     */
    void modelBaseRecordClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    
    /**
     * This method is called after the record with BLOBs class is generated by
     * the ibator supplied JavaModelGenerator.  This method will only be
     * called if the table rules call for generation of a record with BLOBs class.
     * <p/>
     * This method is only guaranteed to be called by the ibator
     * supplied Java model generators.  Other user supplied generators
     * may, or may not, call this method.
     * 
     * @param topLevelClass the generated record with BLOBs class
     * @param introspectedTable ibator's class containing information
     *   about the table as introspected from the database
     */
    void modelRecordWithBLOBsClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    
    /**
     * This method is called after the example class is generated by
     * the ibator supplied JavaModelGenerator.  This method will only be
     * called if the table rules call for generation of an example class.
     * <p/>
     * This method is only guaranteed to be called by the ibator
     * supplied Java model generators.  Other user supplied generators
     * may, or may not, call this method.
     * 
     * @param topLevelClass the generated example class
     * @param introspectedTable ibator's class containing information
     *   about the table as introspected from the database
     */
    void modelExampleClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable);
    
    
    void sqlMapGenerated(GeneratedXmlFile sqlMap, IntrospectedTable introspectedTable);
    void sqlMapDocumentGenerated(Document document, IntrospectedTable introspectedTable);
    void sqlMapBaseResultMapGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapCountByExampleElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapDeleteByExampleElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapDeleteByPrimaryKeyElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapExampleWhereClauseGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapInsertElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapResultMapWithBLOBsGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapSelectByPrimaryKeyElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapSelectByExampleElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapSelectByExampleWithBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapUpdateByExampleSelectiveElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapUpdateByExampleWithBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapUpdateByExampleWithoutBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapUpdateByPrimaryKeySelectiveElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapUpdateByPrimaryKeyWithBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
    void sqlMapUpdateByPrimaryKeyWithoutBLOBsElementGenerated(XmlElement element, IntrospectedTable introspectedTable);
}
