/*
 *  Copyright 2005 The Apache Software Foundation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.apache.ibatis.abator.core.internal.util;

import java.util.Date;

import org.apache.ibatis.abator.core.config.FullyQualifiedTable;
import org.apache.ibatis.abator.core.internal.db.ColumnDefinition;

/**
 * @author Jeff Butler
 */
public class JavadocUtil {

	/**
	 * Utility class - no instances 
	 */
	private JavadocUtil() {
		super();
	}

	public static String getFieldComment(FullyQualifiedTable table, String columnName) {
		StringBuffer comment = new StringBuffer();
		
		comment.append("/**\n");
		comment.append(" * This field was generated by Abator for iBATIS.\n");
		comment.append(" * This field corresponds to the database column ");
		comment.append(table.getFullyQualifiedTableName());
		comment.append('.');
		comment.append(columnName);
		comment.append("\n *\n");
		comment.append(" * @abatorgenerated ");
		comment.append(new Date());
		comment.append("\n */\n");
		
		return comment.toString();
	}
	
	public static String getFieldComment(FullyQualifiedTable table) {
		StringBuffer comment = new StringBuffer();
		
		comment.append("/**\n");
		comment.append(" * This field was generated by Abator for iBATIS.\n");
		comment.append(" * This field corresponds to the database table ");
		comment.append(table.getFullyQualifiedTableName());
		comment.append("\n *\n");
		comment.append(" * @abatorgenerated ");
		comment.append(new Date());
		comment.append("\n */\n");
		
		return comment.toString();
	}
	
	public static String getGetterMethodComment(FullyQualifiedTable table, ColumnDefinition columnDefinition) {
		StringBuffer comment = new StringBuffer();
		
		comment.append("/**\n");
		comment.append(" * This method was generated by Abator for iBATIS.\n");
		comment.append(" * This method returns the value of the database column ");
		comment.append(table.getFullyQualifiedTableName());
		comment.append('.');
		comment.append(columnDefinition.getColumnName());
		comment.append("\n *\n");
		comment.append(" * @return the value of ");
		comment.append(table.getFullyQualifiedTableName());
		comment.append('.');
		comment.append(columnDefinition.getColumnName());
		comment.append("\n *\n");
		comment.append(" * @abatorgenerated ");
		comment.append(new Date());
		comment.append("\n */\n");
		
		return comment.toString();
	}
	
	public static String getSetterMethodComment(FullyQualifiedTable table, ColumnDefinition columnDefinition) {
		StringBuffer comment = new StringBuffer();
		
		comment.append("/**\n");
		comment.append(" * This method was generated by Abator for iBATIS.\n");
		comment.append(" * This method sets the value of the database column ");
		comment.append(table.getFullyQualifiedTableName());
		comment.append('.');
		comment.append(columnDefinition.getColumnName());
		comment.append("\n *\n");
		comment.append(" * @param ");
		comment.append(columnDefinition.getJavaProperty());
		comment.append(" the value for ");
		comment.append(table.getFullyQualifiedTableName());
		comment.append('.');
		comment.append(columnDefinition.getColumnName());
		comment.append("\n *\n");
		comment.append(" * @abatorgenerated ");
		comment.append(new Date());
		comment.append("\n */\n");
		
		return comment.toString();
	}
	
    // TODO - Write better Javadoc for general methods (include return, param and throws)
	public static String getMethodComment(FullyQualifiedTable table) {
		StringBuffer comment = new StringBuffer();
		
		comment.append("/**\n");
		comment.append(" * This method was generated by Abator for iBATIS.\n");
		comment.append(" * This method corresponds to the database table ");
		comment.append(table.getFullyQualifiedTableName());
		comment.append("\n *\n");
		comment.append(" * @abatorgenerated ");
		comment.append(new Date());
		comment.append("\n */\n");
		
		return comment.toString();
	}
}
