/*
 *  Copyright 2008 The Apache Software Foundation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.apache.ibatis.abator.internal;

import java.util.Date;

import org.apache.ibatis.abator.api.CommentGenerator;
import org.apache.ibatis.abator.api.FullyQualifiedTable;
import org.apache.ibatis.abator.api.dom.java.CompilationUnit;
import org.apache.ibatis.abator.api.dom.java.Field;
import org.apache.ibatis.abator.api.dom.java.InnerClass;
import org.apache.ibatis.abator.api.dom.java.InnerEnum;
import org.apache.ibatis.abator.api.dom.java.Method;
import org.apache.ibatis.abator.api.dom.xml.Document;
import org.apache.ibatis.abator.api.dom.xml.TextElement;
import org.apache.ibatis.abator.api.dom.xml.XmlElement;
import org.apache.ibatis.abator.internal.db.ColumnDefinition;

/**
 * @author Jeff Butler
 *
 */
public class DefaultCommentGenerator implements CommentGenerator {

    public void addFieldComment(Field field, FullyQualifiedTable table, String columnName) {
        StringBuffer sb = new StringBuffer();
        
        field.addJavaDocLine("/**"); //$NON-NLS-1$
        field.addJavaDocLine(" * This field was generated by Abator for iBATIS."); //$NON-NLS-1$
        
        sb.append(" * This field corresponds to the database column "); //$NON-NLS-1$
        sb.append(table);
        sb.append('.');
        sb.append(columnName);
        field.addJavaDocLine(sb.toString());
        
        field.addJavaDocLine(" *"); //$NON-NLS-1$
        
        sb.setLength(0);
        sb.append(" * @abatorgenerated "); //$NON-NLS-1$
        sb.append(new Date());
        field.addJavaDocLine(sb.toString());
        
        field.addJavaDocLine(" */"); //$NON-NLS-1$
    }
    
    public void addFieldComment(Field field, FullyQualifiedTable table) {
        StringBuffer sb = new StringBuffer();
        
        field.addJavaDocLine("/**"); //$NON-NLS-1$
        field.addJavaDocLine(" * This field was generated by Abator for iBATIS."); //$NON-NLS-1$
        
        sb.append(" * This field corresponds to the database table "); //$NON-NLS-1$
        sb.append(table);
        field.addJavaDocLine(sb.toString());
        
        field.addJavaDocLine(" *"); //$NON-NLS-1$
        
        sb.setLength(0);
        sb.append(" * @abatorgenerated "); //$NON-NLS-1$
        sb.append(new Date());
        field.addJavaDocLine(sb.toString());

        field.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public void addClassComment(InnerClass innerClass, FullyQualifiedTable table) {
        StringBuffer sb = new StringBuffer();
        
        innerClass.addJavaDocLine("/**"); //$NON-NLS-1$
        innerClass.addJavaDocLine(" * This class was generated by Abator for iBATIS."); //$NON-NLS-1$
        
        sb.append(" * This class corresponds to the database table "); //$NON-NLS-1$
        sb.append(table);
        innerClass.addJavaDocLine(sb.toString());
        
        innerClass.addJavaDocLine(" *"); //$NON-NLS-1$
    
        sb.setLength(0);
        sb.append(" * @abatorgenerated "); //$NON-NLS-1$
        sb.append(new Date());
        innerClass.addJavaDocLine(sb.toString());
        
        innerClass.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public void addEnumComment(InnerEnum innerEnum, FullyQualifiedTable table) {
        StringBuffer sb = new StringBuffer();
        
        innerEnum.addJavaDocLine("/**"); //$NON-NLS-1$
        innerEnum.addJavaDocLine(" * This enum was generated by Abator for iBATIS."); //$NON-NLS-1$
        
        sb.append(" * This enum corresponds to the database table "); //$NON-NLS-1$
        sb.append(table);
        innerEnum.addJavaDocLine(sb.toString());
        
        innerEnum.addJavaDocLine(" *"); //$NON-NLS-1$
    
        sb.setLength(0);
        sb.append(" * @abatorgenerated "); //$NON-NLS-1$
        sb.append(new Date());
        innerEnum.addJavaDocLine(sb.toString());
        
        innerEnum.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public void addGetterComment(Method method, FullyQualifiedTable table, ColumnDefinition columnDefinition) {
        StringBuffer sb = new StringBuffer();
        
        method.addJavaDocLine("/**"); //$NON-NLS-1$
        method.addJavaDocLine(" * This method was generated by Abator for iBATIS."); //$NON-NLS-1$
    
        sb.append(" * This method returns the value of the database column "); //$NON-NLS-1$
        sb.append(table);
        sb.append('.');
        sb.append(columnDefinition.getActualColumnName());
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" *"); //$NON-NLS-1$
        
        sb.setLength(0);
        sb.append(" * @return the value of "); //$NON-NLS-1$
        sb.append(table);
        sb.append('.');
        sb.append(columnDefinition.getActualColumnName());
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" *"); //$NON-NLS-1$
        
        sb.setLength(0);
        sb.append(" * @abatorgenerated "); //$NON-NLS-1$
        sb.append(new Date());
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public void addSetterComment(Method method, FullyQualifiedTable table, ColumnDefinition columnDefinition) {
        StringBuffer sb = new StringBuffer();
        
        method.addJavaDocLine("/**"); //$NON-NLS-1$
        method.addJavaDocLine(" * This method was generated by Abator for iBATIS."); //$NON-NLS-1$
    
        sb.append(" * This method sets the value of the database column "); //$NON-NLS-1$
        sb.append(table);
        sb.append('.');
        sb.append(columnDefinition.getActualColumnName());
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" *"); //$NON-NLS-1$
    
        sb.setLength(0);
        sb.append(" * @param "); //$NON-NLS-1$
        sb.append(columnDefinition.getJavaProperty());
        sb.append(" the value for "); //$NON-NLS-1$
        sb.append(table);
        sb.append('.');
        sb.append(columnDefinition.getActualColumnName());
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" *"); //$NON-NLS-1$
        
        sb.setLength(0);
        sb.append(" * @abatorgenerated "); //$NON-NLS-1$
        sb.append(new Date());
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public void addGeneralMethodComment(Method method, FullyQualifiedTable table) {
        StringBuffer sb = new StringBuffer();
        
        method.addJavaDocLine("/**"); //$NON-NLS-1$
        method.addJavaDocLine(" * This method was generated by Abator for iBATIS."); //$NON-NLS-1$
        
        sb.append(" * This method corresponds to the database table "); //$NON-NLS-1$
        sb.append(table);
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" *"); //$NON-NLS-1$
    
        sb.setLength(0);
        sb.append(" * @abatorgenerated "); //$NON-NLS-1$
        sb.append(new Date());
        method.addJavaDocLine(sb.toString());
        
        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    public void addJavaFileComment(CompilationUnit compilationUnit) {
        // add no file level comments by default
        ;
    }

    /**
     * Adds a suitable comment to warn users that the element was generated, and
     * when it was generated.
     */
    public void addComment(XmlElement xmlElement) {
        xmlElement.addElement(new TextElement("<!--")); //$NON-NLS-1$
        xmlElement.addElement(new TextElement(
                "  WARNING - This element is automatically generated by Abator for iBATIS, do not modify.")); //$NON-NLS-1$

        StringBuffer sb = new StringBuffer();
        sb.append("  This element was generated on "); //$NON-NLS-1$
        sb.append(new Date());
        sb.append('.');
        xmlElement.addElement(new TextElement(sb.toString()));

        xmlElement.addElement(new TextElement("-->")); //$NON-NLS-1$
    }

    public void addComment(Document document) {
        // add no document level comments by default
        ;
    }
}
